name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  APPLICATION: Shasta
  PACKAGE_VERSION: 1.0.0.1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
      env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Display dotnet version
      run: dotnet --version
    - name: add package source - strike
      run: dotnet nuget add source --username karanbajaj --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/STRIKE-HEALTH/index.json"
    - name: add package source - karan
      run: dotnet nuget add source --username karanbajaj --password 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 --store-password-in-clear-text --name github-karan "https://nuget.pkg.github.com/karanbajaj/index.json"
    - name: package sources
      run: dotnet nuget list source 
    - name: Restore dependencies
      run: dotnet restore App.Metrics.Reporting.CloudWatch.csproj
    - name: Build
      run: dotnet build -c release --no-restore App.Metrics.Reporting.CloudWatch.csproj
    - name: Publish
      run: |
        dotnet publish -c Release --version-suffix $GITHUB_RUN_NUMBER  -o ./Publish -r win-x64 --self-contained false  App.Metrics.Reporting.CloudWatch.csproj

    - name: Test
      run: dotnet test --no-build --verbosity normal App.Metrics.Reporting.CloudWatch.csproj
    - name: Pack Project 
      run: dotnet pack --configuration Release App.Metrics.Reporting.CloudWatch.csproj
    
        
    
    
    
